# TODO add some notes about how to override these 

# backend:
#   database:
#     connection:
#       host: 127.0.0.1
#       port: 5432
#       user: postgres
#       password: postgres
#   cors:
#     origin: '*'
#     methods: [GET, POST, PUT, DELETE]
#     credentials: true
# auth:
#   providers: 
#     github:
#       development:
#         clientId: ${secrets.AUTH_GITHUB_CLIENT_ID}
#         clientSecret: ${secrets.AUTH_GITHUB_CLIENT_SECRET}
# techdocs:
#   publisher:
#     awsS3: 
#       bucketName: ${secrets.TECHDOCS_S3_BUCKET_NAME}
#       region: ${secrets.AWS_REGION}
#       credentials:
#         accessKeyId: ${secrets.AWS_ACCESS_KEY_ID}
#         secretAccessKey: ${secrets.AWS_SECRET_ACCESS_KEY}
